@include('front_layout/header')
@include('front_layout/navbar')
@include( 'front_layout/home')
@include( 'front_layout/services')
@include( 'front_layout/about-us')
@include( 'front_layout/team')
@include( 'front_layout/gallery')
@include( 'front_layout/testimonial')
@include( 'front_layout/blog')
@include( 'front_layout/newsletter')
@include( 'front_layout/contact-us')
@include( 'front_layout/sortportfolio')
@include('front_layout/footer')